name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y lcov

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build

      - name: Coverage
        run: |
          lcov --capture --directory ${{github.workspace}}/build --output-file ${{github.workspace}}/coverage.info
          lcov --remove ${{github.workspace}}/coverage.info '/usr/*' --output-file ${{github.workspace}}/coverage.info



